spring:
  application:
    name: config

  profiles:
    active:
    - ${PROFILE:dev}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE